controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  left_arm_controller:
    type: gravity_compensation_controller/GravityCompensationJointTrajectoryController
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
    gains:
      left_joint1: { p: 100, i: 2.0, d: 2.0, i_clamp_max: 5, i_clamp_min: -5, antiwindup: true, publish_state: false }
      left_joint2: { p: 150, i: 5.0, d: 5.0, i_clamp_max: 6, i_clamp_min: -6, antiwindup: true, publish_state: false }
      left_joint3: { p: 100, i: 1.0, d: 1.0, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: false }
      left_joint4: { p: 120, i: 5.0, d: 2.0, i_clamp_max: 3, i_clamp_min: -3, antiwindup: true, publish_state: false }
      left_joint5: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      left_joint6: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state： false }
      left_joint7: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      left_joint1: { trajectory: 0.08, goal: 0.05 }
      left_joint2: { trajectory: 0.08, goal: 0.05 }
      left_joint3: { trajectory: 0.08, goal: 0.05 }
      left_joint4: { trajectory: 0.08, goal: 0.05 }
      left_joint5: { trajectory: 0.08, goal: 0.05 }
      left_joint6: { trajectory: 0.08, goal: 0.05 }
      left_joint7: { trajectory: 0.08, goal: 0.05 }
    tau_g_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  right_arm_controller:
    type: gravity_compensation_controller/GravityCompensationJointTrajectoryController
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
    gains:
      right_joint1: { p: 100, i: 2.0, d: 2.0, i_clamp_max: 5, i_clamp_min: -5, antiwindup: true, publish_state: false }
      right_joint2: { p: 150, i: 5.0, d: 5.0, i_clamp_max: 6, i_clamp_min: -6, antiwindup: true, publish_state: false }
      right_joint3: { p: 100, i: 1.0, d: 1.0, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: false }
      right_joint4: { p: 120, i: 5.0, d: 2.0, i_clamp_max: 3, i_clamp_min: -3, antiwindup: true, publish_state: false }
      right_joint5: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      right_joint6: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
      right_joint7: { p: 30, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      right_joint1: { trajectory: 0.08, goal: 0.05 }
      right_joint2: { trajectory: 0.08, goal: 0.05 }
      right_joint3: { trajectory: 0.08, goal: 0.05 }
      right_joint4: { trajectory: 0.08, goal: 0.05 }
      right_joint5: { trajectory: 0.08, goal: 0.05 }
      right_joint6: { trajectory: 0.08, goal: 0.05 }
      right_joint7: { trajectory: 0.08, goal: 0.05 }
    tau_g_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  gimbal_arm_controller:
    type: gravity_compensation_controller/GravityCompensationJointTrajectoryController
    joints:
      - main_pitch
      - gimbal_joint1
      - gimbal_joint2
      - gimbal_joint3
    gains:
      main_pitch: { p: 350, i: 25.0, d: 7.0, i_clamp_max: 10, i_clamp_min: -10, antiwindup: true, publish_state: false }
      gimbal_joint1: { p: 100.0, i: 10.0, d: 5.0, i_clamp_max: 3, i_clamp_min: -3, antiwindup: true, publish_state: false }
      gimbal_joint2: { p: 100.0, i: 10.0, d: 5.0, i_clamp_max: 3, i_clamp_min: -3, antiwindup: true, publish_state: false }
      gimbal_joint3: { p: 10.0, i: 1.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: false }
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      main_pitch: { trajectory: 0.08, goal: 0.05 }
      gimbal_joint1: { trajectory: 0.08, goal: 0.05 }
      gimbal_joint2: { trajectory: 0.08, goal: 0.05 }
      gimbal_joint3: { trajectory: 0.08, goal: 0.05 }
    tau_g_scale: [0.0, 1.0, 1.0, 1.0]

  chassis_controller:
    type: rm_chassis_controllers/SwerveController
    # ChassisBase
    publish_rate: 100
    publish_map_tf: false
    publish_odom_tf: true
    slam_topic: "/Odometry"
    localization_topic: "/hdl_global_localization/result"
    power:
      effort_coeff: 1.8
      vel_coeff: 0.01
      power_offset: 7.0
      pivot_max_power: 50
      pivot_effort_coeff: 50
      pivot_vel_coeff: 0.01
      pivot_power_ratio: 0.8
      power_factor: -0.2
      use_rls: false
      use_K_angle: true
    twist_angular: 0.5233
    max_odom_vel: 10.0
    timeout: 0.1
    pid_follow: { p: 6.5, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # SwerveController
    modules:
      left_front:
        position: [ 0.205, 0.200 ]
        pivot:
          joint: left_front_pivot_joint
          <<: &pivot_setting
            buffer_threshold: 10.0
            offset: 0.
            pid: { p: 4.5, i: 0, d: 0.03, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: false }
        wheel:
          joint: left_front_wheel_joint
          <<: &wheel_setting
            radius: 0.061
            pid: { p: 0.35, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: false }
      right_front:
        position: [ 0.205, -0.200 ]
        pivot:
          joint: right_front_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_front_wheel_joint
          <<: *wheel_setting
      left_back:
        position: [ -0.205, 0.200 ]
        pivot:
          joint: left_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: left_back_wheel_joint
          <<: *wheel_setting
      right_back:
        position: [ -0.205, -0.200 ]
        pivot:
          joint: right_back_pivot_joint
          <<: *pivot_setting
        wheel:
          joint: right_back_wheel_joint
          <<: *wheel_setting
