controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      joint1: { trajectory: 0.08, goal: 0.05 }
      joint2: { trajectory: 0.08, goal: 0.05 }
      joint3: { trajectory: 0.08, goal: 0.05 }
      joint4: { trajectory: 0.08, goal: 0.05 }
      joint5: { trajectory: 0.08, goal: 0.05 }
      joint6: { trajectory: 0.08, goal: 0.05 }
      joint7: { trajectory: 0.08, goal: 0.05 }
    gains:
      joint1: { p: 16000, i: 100, d: 500.0, i_clamp_max: 10, i_clamp_min: -10, antiwindup: true, publish_state: true }
      joint2: { p: 100, i: 5, d: 10, i_clamp_max: 5, i_clamp_min: -5, antiwindup: true, publish_state: true }
      joint3: { p: 1000, i: 100, d: 20, i_clamp_max: 10, i_clamp_min: -10, antiwindup: true, publish_state: true }
      joint4: { p: 500, i: 1, d: 5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
      joint5: { p: 200, i: 1, d: 2, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
      joint6: { p: 100, i: 1, d: 1, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
      joint7: { p: 100, i: 1, d: 1, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
      
  gravity_compensation_controller:
    type: gravity_compensation_controller/GravityCompensationJointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    gains:
      joint1: { p: 16000.0, i: 10.0, d: 580.0, i_clamp_max: 20, i_clamp_min: -20, antiwindup: true, publish_state: true }
      joint2: { p: 60.0, i: 0.015, d: 1.8, i_clamp_max: 7, i_clamp_min: -7, antiwindup: true, publish_state: true }
      joint3: { p: 135.0, i: 35.0, d: 3.5, i_clamp_max: 0, i_clamp_min: -16, antiwindup: true, publish_state: true }
      joint4: { p: 85.0, i: 9.0, d: 2.0, i_clamp_max: 0, i_clamp_min: -9, antiwindup: true, publish_state: true }
      joint5: { p: 24.0, i: 1.5, d: 0.4, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }
      joint6: { p: 18.0, i: 4.0, d: 0.5, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
      joint7: { p: 17.0, i: 1.2, d: 0.4, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      joint1: { trajectory: 0.08, goal: 0.05 }
      joint2: { trajectory: 0.08, goal: 0.05 }
      joint3: { trajectory: 0.08, goal: 0.05 }
      joint4: { trajectory: 0.08, goal: 0.05 }
      joint5: { trajectory: 0.08, goal: 0.05 }
      joint6: { trajectory: 0.08, goal: 0.05 }
      joint7: { trajectory: 0.08, goal: 0.05 }
    offset_torques: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    tau_g_scale: [0.0, 1.0, 0.57, 0.625, 1.0, 1.0, 1.0]
    chain_root: base_link
    chain_tip: gripper_link

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 2.0
      vel_coeff: 0.008
      power_offset: -9.8
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 4.0, i: 0, d: 0.02, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
    max_odom_vel: 10.0
    # OmniController
    wheels:
      left_front:
        pose: [ 0.213, 0.1945, 0. ]
        roller_angle: -0.785
        joint: left_front_wheel_joint
        <<: &wheel_setting
          radius: 0.07
          pid: { p: 0.3, i: 0.2, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true, publish_state: false }
      right_front:
        pose: [ 0.213, -0.1945, 0. ]
        roller_angle: 0.785
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.213, 0.1945, 0. ]
        roller_angle: 0.785
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.213, -0.1945, 0. ]
        roller_angle: -0.785
        joint: right_back_wheel_joint
        <<: *wheel_setting

#  gimbal_controller:
#    type: rm_gimbal_controllers/Controller
#    yaw:
#      joint: "yaw_joint"
#      pid: { p: 0.5, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: false }
#      pid_pos: { p: 15.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
#      k_chassis_vel: 0.035
#      k_v: 1.0
#    pitch:
#      joint: "pitch_joint"
#      pid: { p: 0., i: 0.0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: false }
#      pid_pos: { p: 0.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
#      k_v: 1.0
#    feedforward:
#      gravity: 0.0
#      enable_gravity_compensation: false
#      mass_origin: [ 0.0,0.0,0.0 ]
#    bullet_solver:
#      resistance_coff_qd_10: 0.45
#      resistance_coff_qd_15: 1.0
#      resistance_coff_qd_16: 0.7
#      resistance_coff_qd_18: 0.55
#      resistance_coff_qd_30: 3.0
#      g: 9.81
#      delay: 0.1
#      dt: 0.001
#      timeout: 0.001
#      publish_rate: 50
