# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_joint1:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint2:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint3:
    has_velocity_limits: true
    max_velocity: 3.76
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint4:
    has_velocity_limits: true
    max_velocity: 3.76
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint5:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint6:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: true
    max_acceleration: 10
  left_joint7:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint1:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint2:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint3:
    has_velocity_limits: true
    max_velocity: 3.76
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint4:
    has_velocity_limits: true
    max_velocity: 3.76
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint5:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint6:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  right_joint7:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  main_pitch:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  gimbal_joint1:
    has_velocity_limits: true
    max_velocity: 3.76
    has_acceleration_limits: true
    max_acceleration: 10
  gimbal_joint2:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10
  gimbal_joint3:
    has_velocity_limits: true
    max_velocity: 10.46
    has_acceleration_limits: true
    max_acceleration: 10